// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6JtsDkjjZ2V9b6FMVQzrY2eoXGLJKZs4',
    appId: '1:760642321243:web:e11b346159e19b5513787e',
    messagingSenderId: '760642321243',
    projectId: 'mobile-7ac66',
    authDomain: 'mobile-7ac66.firebaseapp.com',
    storageBucket: 'mobile-7ac66.firebasestorage.app',
    measurementId: 'G-5SMDYJDT4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvi8ffOfu8qLCja5I9T5LbmNcH1O7t4R0',
    appId: '1:760642321243:android:0636700e872ddaf913787e',
    messagingSenderId: '760642321243',
    projectId: 'mobile-7ac66',
    storageBucket: 'mobile-7ac66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADfVXKOYGb3tivC_bxdHhXKTiuQL2N7F4',
    appId: '1:760642321243:ios:a8f27f30432c005c13787e',
    messagingSenderId: '760642321243',
    projectId: 'mobile-7ac66',
    storageBucket: 'mobile-7ac66.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADfVXKOYGb3tivC_bxdHhXKTiuQL2N7F4',
    appId: '1:760642321243:ios:a8f27f30432c005c13787e',
    messagingSenderId: '760642321243',
    projectId: 'mobile-7ac66',
    storageBucket: 'mobile-7ac66.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6JtsDkjjZ2V9b6FMVQzrY2eoXGLJKZs4',
    appId: '1:760642321243:web:3be9207b7709f1ab13787e',
    messagingSenderId: '760642321243',
    projectId: 'mobile-7ac66',
    authDomain: 'mobile-7ac66.firebaseapp.com',
    storageBucket: 'mobile-7ac66.firebasestorage.app',
    measurementId: 'G-LC8D60N9XE',
  );
}
